name: georgiaonmydime
description: The universal codebase for the Android&#x2F;iOS Georgia On My Dime application

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^3.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/gomd_title.png

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-Light.ttf
        - asset: fonts/Quicksand-Bold.ttf
